"""empty message

Revision ID: 687379ae129a
Revises: 
Create Date: 2020-01-09 00:43:19.461951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687379ae129a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('instance', sa.SmallInteger(), nullable=True),
    sa.Column('docname', sa.String(length=120), nullable=True),
    sa.Column('page', sa.String(length=7), nullable=True),
    sa.Column('case_number', sa.SmallInteger(), nullable=True),
    sa.Column('case_tom', sa.SmallInteger(), nullable=True),
    sa.Column('case', sa.String(length=120), nullable=True),
    sa.Column('date_doc', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('document')
    # ### end Alembic commands ###
