"""empty message

Revision ID: 7530061615a3
Revises: d94f7fc5a8a5
Create Date: 2019-12-17 22:09:16.868305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7530061615a3'
down_revision = 'd94f7fc5a8a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('instance', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'instance')
    # ### end Alembic commands ###
