"""empty message

Revision ID: b18a6d0c528f
Revises: 7530061615a3
Create Date: 2019-12-17 22:55:14.412455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18a6d0c528f'
down_revision = '7530061615a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('page', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'page')
    # ### end Alembic commands ###
